config/routes.rb
Rails.application.routes.draw do
  resources :candies
  resources :kids
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candy.rb
class Candy < ApplicationRecord
  has_and_belongs_to_many :kids
end

app/models/kid.rb
class Kid < ApplicationRecord
    has_and_belongs_to_many :candies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  before_action :set_candy, only: [:show, :edit, :update, :destroy]

  # GET /candies
  # GET /candies.json
  def index
    @candies = Candy.all
  end

  # GET /candies/1
  # GET /candies/1.json
  def show
  end

  # GET /candies/new
  def new
    @candy = Candy.new
    @kids = Kid.all
  end

  # GET /candies/1/edit
  def edit
    @kids = Kid.all
  end

  # POST /candies
  # POST /candies.json
  def create
    @candy = Candy.new(candy_params)

    respond_to do |format|
      if @candy.save
        format.html { redirect_to @candy, notice: 'Candy was successfully created.' }
        format.json { render :show, status: :created, location: @candy }
      else
        format.html { render :new }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candies/1
  # PATCH/PUT /candies/1.json
  def update
    respond_to do |format|
      if @candy.update(candy_params)
        format.html { redirect_to @candy, notice: 'Candy was successfully updated.' }
        format.json { render :show, status: :ok, location: @candy }
      else
        format.html { render :edit }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candies/1
  # DELETE /candies/1.json
  def destroy
    @candy.destroy
    respond_to do |format|
      format.html { redirect_to candies_url, notice: 'Candy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candy
      @candy = Candy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candy_params
      params.require(:candy).permit(:name, kid_ids: [])
    end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
  end

  # GET /kids/new
  def new
    @kid = Kid.new
    @candies = Candy.all   
  end

  # GET /kids/1/edit
  def edit
    @candies = Candy.all
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { render :show, status: :ok, location: @kid }
      else
        format.html { render :edit }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url, notice: 'Kid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kid
      @kid = Kid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kid_params
      params.require(:kid).permit(:name, :candy_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candies_helper.rb
module CandiesHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/candies/_form.html.erb
<%= form_with(model: candy, local: true) do |form| %>
  <% if candy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candy.errors.count, "error") %> prohibited this candy from being saved:</h2>

      <ul>
      <% candy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :candy_name %>
  </div>

  <div class="field">
   <%= collection_check_boxes(:candy, :kid_ids, @kids, :id, :name) %>                            
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/candies/edit.html.erb
<h1>Editing Candy</h1>

<%= render 'form', candy: @candy %>

<%= link_to 'Show', @candy %> |
<%= link_to 'Back', candies_path %>

app/views/candies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kids</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candies.each do |candy| %>
      <tr>
        <td><%= candy.name %></td>
        <td><%= candy.kids.map {|k| k.name}.join(', ') %></td>
        <td><%= link_to 'Show', candy %></td>
        <td><%= link_to 'Edit', edit_candy_path(candy) %></td>
        <td><%= link_to 'Destroy', candy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candy', new_candy_path %>

app/views/candies/new.html.erb
<h1>New Candy</h1>

<%= render 'form', candy: @candy %>

<%= link_to 'Back', candies_path %>

app/views/candies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candy.name %>
</p>

<p>
  <strong>Kid's name:</strong>
  <%= @candy.kids.map {|k| k.name}.join(', ') %>
</p>

<%= link_to 'Edit', edit_candy_path(@candy) %> |
<%= link_to 'Back', candies_path %>

app/views/kids/_form.html.erb
<%= form_with(model: kid, local: true) do |form| %>
  <% if kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kid.errors.count, "error") %> prohibited this kid from being saved:</h2>

      <ul>
      <% kid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :kid_name %>
  </div>

  <div class="field">
    <%= collection_check_boxes(:kid, :candy_ids, @candies, :id, :name) %>                            
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kids/edit.html.erb
<h1>Editing Kid</h1>

<%= render 'form', kid: @kid %>

<%= link_to 'Show', @kid %> |
<%= link_to 'Back', kids_path %>

app/views/kids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Candies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kids.each do |kid| %>
      <tr>
        <td><%= kid.name %></td>
        <td><%= kid.candies.map {|c| c.name}.join(', ') %></td>
        <td><%= link_to 'Show', kid %></td>
        <td><%= link_to 'Edit', edit_kid_path(kid) %></td>
        <td><%= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kid', new_kid_path %>

app/views/kids/new.html.erb
<h1>New Kid</h1>

<%= render 'form', kid: @kid %>

<%= link_to 'Back', kids_path %>

app/views/kids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kid.name %>
</p>

<p>
  <strong>Candy name:</strong>
  <%= @kid.candies.map {|c| c.name}.join(', ') %>
</p>


<%= link_to 'Edit', edit_kid_path(@kid) %> |
<%= link_to 'Back', kids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Holloween</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>